var searchparameters = {
	"AllergyIntolerance" : "identifier,patient,category,status,substance,manifestation,severity,duration,onset",
	"DiagnosticOrder" : "identifier,patient,orderer,code,encounter,item-date",
	"DiagnosticReport" : "identifier,patient,name,date,encounter,performer,result",
	"Encounter" : "identifier,patient,location,type,date,location-period",
	"FamilyMemberHistory" : "identifier,patient,relationship,familyhistorycondition",
	"Immunization" : "identifier,patient,date,vaccine-type,notgiven,lot-number,requester",
	//"Observation" : "identifier,patient,code,value-concept,value-quantity,code-value[x],date,encounter",
	"Medication" : "identifier,code,name,form,ingredient",
	"MedicationStatement" : "identifier,patient,effectivedate,medication",
	"MedicationAdministration" : "identifier,patient,effectivetime,encounter,practitioner,prescription",
	"Patient" : "name,family,given,identifier,language,telecom,gender,birthdate,city,postalcode,state,mothersMaidenName,age,race,ethnicity",
	"Condition" : "identifier,code,date-Asserted,encounter,onset,patient,severity",
	"Procedure" : "identifier,type,date,patient,encounter",
	//"Observation" : "identifier,date,value-concept,patient",
	//"Observation" : "identifier,date,value-quantity,code,code-value[x],patient",
	"List" : "identifier,code,date,empty-reason,patient",
	"DocumentReference" : "subject,subject.identifier,identifier,created,period,status,type"
}

var matchcriterian = {
	"subject":"Exact,Exact Ignore Case,Contains",
	"subject.identifier" : "Exact,Exact Ignore Case,Contains",
	"identifier" : "Exact,Exact Ignore Case,Contains",
	"patient" : "Exact,Exact Ignore Case,Contains",
	"category" : "Exact,Exact Ignore Case,Contains",
	"status" :"Exact,Exact Ignore Case,Contains",
	"substance" : "Exact,Exact Ignore Case,Contains",
	"manifestation" : "Exact,Exact Ignore Case,Contains",
	"severity" : "Exact,Exact Ignore Case,Contains",
	"duration" : "Exact,Exact Ignore Case,Contains",
	"onset" : "Before,After,Between",
	"orderer" : "Exact,Exact Ignore Case,Contains",
	"code" : "Exact,Exact Ignore Case,Contains",
	"encounter" : "Exact,Exact Ignore Case,Contains",
	"item-date" : "Before,After,Between",
	"name" : "Exact,Exact Ignore Case,Contains",
	"date" :"Before,After,Between",
	"created" : ">,<,=",
	"period" : ">,<,=",
	"performer" : "Exact,Exact Ignore Case,Contains",
	"result" : "Exact,Exact Ignore Case,Contains",
	"location" :"Exact,Exact Ignore Case,Contains",
	"type" : "Exact,Exact Ignore Case,Contains",
	"location-period" :"Before,After,Between",
	"relationship" : "Exact,Exact Ignore Case,Contains",
	"familyhistorycondition" : "Exact,Exact Ignore Case,Contains",
	"vaccine-type" : "Exact,Exact Ignore Case,Contains",
	"notgiven" : "Exact,Exact Ignore Case,Contains",
	"lot-number" : "Exact,Exact Ignore Case,Contains",
	"requester" : "Exact,Exact Ignore Case,Contains",
	"value-concept" : "Exact,Exact Ignore Case,Contains",
	"value-quantity" : "Exact,Exact Ignore Case,Contains",
	"code-value[x]" : "Exact,Exact Ignore Case,Contains",
	"form" : "Exact,Exact Ignore Case,Contains",
	"ingredient" : "Exact,Exact Ignore Case,Contains",
	"effectivedate" :"Before,After,Between",
	"medication" : "Exact,Exact Ignore Case,Contains",
	"effectivetime" :"Before,After,Between",
	"practitioner" : "Exact,Exact Ignore Case,Contains",
	"prescription" : "Exact,Exact Ignore Case,Contains",
	"family" : "Exact,Exact Ignore Case,Contains",
	"given" : "Exact,Exact Ignore Case,Contains",
	"language" : "Exact,Exact Ignore Case,Contains",
	"telecom" : "Exact,Exact Ignore Case,Contains",
	"gender" : "Exact,Exact Ignore Case,Contains",
	"birthdate" :"Before,After,Between",
	"city" : "Exact,Exact Ignore Case,Contains",
	"postalcode" : "Exact,Exact Ignore Case,Contains",
	"state" : "Exact,Exact Ignore Case,Contains",
	"mothersMaidenName" : "Exact,Exact Ignore Case,Contains",
	"age" : "=,<,>,<=,>=",
	"race" : "Exact,Exact Ignore Case,Contains",
	"ethnicity" : "Exact,Exact Ignore Case,Contains",
	"date-Asserted" :"Before,After,Between",
	"empty-reason" : "Exact,Exact Ignore Case,Contains",
}